'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { ShieldCheck, ArrowRight } from 'lucide-react';
import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';

interface SafetyPrinciple {
  num: string;
  id: string;
  title: string;
  shortDesc: string;
  fullDetail: string;
}

const SAFETY_PRINCIPLES: SafetyPrinciple[] = [
  {
    num: '01',
    id: 'only-group-sees-you',
    title: 'Only your group sees you',
    shortDesc: 'A member’s location is only ever visible to other active members of the same group, on the same trip — never anyone else.',
    fullDetail: 'Location streaming is scoped strictly to the current active trip session. It is never exposed as a public endpoint, indexable directory, or third-party broadcast.',
  },
  {
    num: '02',
    id: 'every-request-verified',
    title: 'Every request is verified',
    shortDesc: 'Every request is tied to a verified, signed-in account. Nobody can submit or view location data on someone else’s behalf.',
    fullDetail: 'All WebSocket telemetry streams and API queries require active session signature authentication, ensuring data isolation across groups.',
  },
  {
    num: '03',
    id: 'leaving-always-available',
    title: 'Leaving is always available',
    shortDesc: 'Any member can leave a group at any time, and a leader can remove a member — access ends the moment membership does.',
    fullDetail: 'Leaving a group instantly revokes all real-time stream permissions and access to active trip telemetry.',
  },
  {
    num: '04',
    id: 'one-tap-sos',
    title: 'One-tap SOS',
    shortDesc: 'When something goes wrong, a single confirmation shares your exact location with the whole group immediately.',
    fullDetail: 'SOS overrides standard interval buffering to transmit high-priority coordinate bursts directly to active group members.',
  },
  {
    num: '05',
    id: 'join-codes-not-open-access',
    title: 'Join codes, not open access',
    shortDesc: 'Groups are only joinable with a code from the leader — there’s no public directory of groups or trips.',
    fullDetail: 'Groups are private by default. Without a direct invite code generated by the group leader, a group cannot be found or requested.',
  },
  {
    num: '06',
    id: 'history-not-surveillance',
    title: 'History, not surveillance',
    shortDesc: 'Trip history exists so a journey can be understood after the fact — it’s scoped to the group and trip it belongs to, nothing wider.',
    fullDetail: 'Historical trip records are preserved for post-trip replay within the group archive, but live location feeds close permanently when a trip ends.',
  },
];

export default function SafetyInteractive() {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const togglePrinciple = (id: string) => {
    setExpandedId((prev) => (prev === id ? null : id));
  };

  return (
    <div className="bg-[#000000] text-white min-h-screen font-sans selection:bg-white/20 selection:text-white">
      {/* Global Navbar */}
      <Navbar />

      {/* 2. HERO SECTION — Spacious & Intentional (90-110px top, 70-90px bottom on mobile) */}
      <section className="pt-[90px] sm:pt-28 pb-[70px] sm:pb-24 px-6 max-w-5xl mx-auto text-center flex flex-col items-center">
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/[0.04] border border-white/10 text-xs font-mono tracking-[0.2em] text-white/70 uppercase mb-6"
        >
          <ShieldCheck className="w-3.5 h-3.5 text-white/70" />
          SAFETY
        </motion.div>

        {/* Hero headline: 38-44px on mobile, max-w-[360px] mobile width */}
        <motion.h1
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-[38px] sm:text-6xl font-medium tracking-tight text-white max-w-[360px] sm:max-w-3xl leading-[1.08]"
        >
          Safety, built into <br />
          <span className="font-serif italic font-normal text-white/90 tracking-normal">
            how RALLY works — not bolted on.
          </span>
        </motion.h1>

        {/* Hero supporting text: 13-15px on mobile, max-w-[320px] mobile width */}
        <motion.p
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-6 text-xs sm:text-base text-white/60 max-w-[320px] sm:max-w-2xl font-normal leading-relaxed"
        >
          Location is sensitive data. RALLY is built so it&apos;s only ever visible to the people it&apos;s meant for, for exactly as long as it&apos;s needed.
        </motion.p>

        {/* System status indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.3 }}
          className="mt-8 flex items-center gap-2 font-mono text-xs text-white/50 border border-white/10 px-3.5 py-1.5 rounded-full bg-white/[0.02]"
        >
          <span className="w-1.5 h-1.5 rounded-full bg-white animate-pulse" />
          <span>PRIVATE BY DEFAULT</span>
        </motion.div>
      </section>

      {/* Hero Subtle Divider */}
      <div className="max-w-5xl mx-auto px-6">
        <hr className="border-white/10" />
      </div>

      {/* MAIN CONTENT AREA WITH SIGNATURE VISIBILITY LINE */}
      <div className="max-w-[1100px] mx-auto px-6 relative">
        {/* Thin vertical signature visibility line */}
        <div className="hidden md:block absolute left-6 top-0 bottom-0 w-[1px] bg-gradient-to-b from-white/20 via-white/10 to-transparent pointer-events-none" />

        {/* 4. LARGE EDITORIAL STATEMENT (Generous spacing: 120-180px!) */}
        <section className="py-28 sm:py-36 max-w-3xl">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-6">
            HOW RALLY THINKS ABOUT SAFETY
          </div>

          <h2 className="text-[28px] sm:text-5xl font-medium tracking-tight text-white leading-[1.08] font-sans max-w-[350px] sm:max-w-3xl">
            Your location belongs to the group you&apos;re traveling with — <br className="hidden sm:block" />
            <span className="font-serif italic font-normal text-white/85">
              and only for as long as the trip requires it.
            </span>
          </h2>
        </section>

        {/* 5. SAFETY PRINCIPLES (Clear Hierarchy & Generous Spacing!) */}
        <section className="py-16 sm:py-24 border-t border-white/10">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-10">
            SAFETY & PRIVACY SPECIFICATION
          </div>

          <div className="divide-y divide-white/10">
            {SAFETY_PRINCIPLES.map((principle) => {
              const isExpanded = expandedId === principle.id;
              return (
                <div key={principle.id} className="py-7 sm:py-9 transition-all duration-200">
                  <button
                    onClick={() => togglePrinciple(principle.id)}
                    aria-expanded={isExpanded}
                    aria-controls={`principle-detail-${principle.id}`}
                    className="w-full text-left group focus:outline-none flex flex-col md:flex-row md:items-start justify-between gap-4"
                  >
                    <div className="flex flex-col md:flex-row md:items-start gap-3 md:gap-8 max-w-3xl">
                      {/* Principle Number */}
                      <span className="font-mono text-xs text-white/40 group-hover:text-white transition-colors pt-0.5">
                        {principle.num}
                      </span>

                      <div className="space-y-3">
                        {/* Principle Title: 16-19px mobile, 18-22px desktop (Visually Dominant!) */}
                        <div className="text-[17px] sm:text-xl font-medium text-white group-hover:translate-x-1 transition-transform flex items-center justify-between md:justify-start gap-4">
                          <span>{principle.title}</span>
                          <span className="text-xs font-mono text-white/40 group-hover:text-white/80">
                            {isExpanded ? '− LESS' : '+ MORE'}
                          </span>
                        </div>

                        {/* Principle Description: 13-14px mobile */}
                        <p className="text-xs sm:text-base text-white/60 leading-[1.6] font-normal max-w-2xl">
                          {principle.shortDesc}
                        </p>
                      </div>
                    </div>
                  </button>

                  {/* Expandable Inline Detail */}
                  <AnimatePresence initial={false}>
                    {isExpanded && (
                      <motion.div
                        id={`principle-detail-${principle.id}`}
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                        className="overflow-hidden md:pl-14 pt-4"
                      >
                        <div className="p-4 rounded-lg bg-white/[0.03] border-l-2 border-white/30 font-mono text-xs text-white/70 leading-relaxed">
                          <span className="text-white font-bold block mb-1">SYSTEM SPECIFICATION:</span>
                          {principle.fullDetail}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </section>

        {/* 8. VISIBILITY TIMELINE */}
        <section className="py-24 sm:py-32 border-t border-white/10">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-8">
            WHEN LOCATION IS VISIBLE
          </div>

          <div className="p-6 sm:p-8 rounded-2xl bg-[#030303] border border-white/10 font-mono text-xs">
            {/* Desktop Horizontal / Mobile Vertical Layout */}
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6 sm:gap-4 text-white/70">
              <div className="text-left">
                <span className="font-bold text-white text-sm block">JOIN</span>
                <span className="text-xs text-white/40">Invite Code Verified</span>
              </div>

              <div className="hidden sm:block flex-1 h-[1px] bg-white/20 mx-3" />
              <div className="sm:hidden w-[1px] h-6 bg-white/20 ml-3 my-1" />

              <div className="text-left">
                <span className="font-bold text-white text-sm block">TRIP ACTIVE</span>
                <span className="text-xs text-white/40">Trip Started</span>
              </div>

              <div className="hidden sm:block flex-1 h-[1px] bg-white/20 mx-3" />
              <div className="sm:hidden w-[1px] h-6 bg-white/20 ml-3 my-1" />

              <div className="text-left">
                <span className="font-bold text-emerald-400 text-sm block">GROUP MEMBERS</span>
                <span className="text-xs text-emerald-400/70">Scoped Live Feed</span>
              </div>

              <div className="hidden sm:block flex-1 h-[1px] bg-white/20 mx-3" />
              <div className="sm:hidden w-[1px] h-6 bg-white/20 ml-3 my-1" />

              <div className="text-left sm:text-right">
                <span className="font-bold text-white text-sm block">TRIP ENDS</span>
                <span className="text-xs text-white/40">Stream Closed</span>
              </div>
            </div>
          </div>
        </section>

        {/* 9. WHO CAN SEE YOUR LOCATION */}
        <section className="py-20 sm:py-28 border-t border-white/10 font-mono text-xs">
          <div className="text-xs text-white/40 uppercase tracking-[0.2em] mb-10">
            WHO CAN SEE YOUR LOCATION?
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 sm:gap-16">
            <div className="space-y-4">
              <div className="text-white font-bold text-sm tracking-wider uppercase border-b border-white/20 pb-3">
                VISIBLE TO
              </div>
              <ul className="space-y-3 text-white/80 font-sans text-xs sm:text-base">
                <li className="flex items-center gap-3">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                  Your active trip group members
                </li>
              </ul>
            </div>

            <div className="space-y-4">
              <div className="text-white font-bold text-sm tracking-wider uppercase border-b border-white/20 pb-3">
                NOT VISIBLE TO
              </div>
              <ul className="space-y-3 text-white/40 font-sans text-xs sm:text-base">
                <li className="flex items-center gap-3">
                  <span className="w-1.5 h-1.5 rounded-full bg-white/20" />
                  Public users or search engines
                </li>
                <li className="flex items-center gap-3">
                  <span className="w-1.5 h-1.5 rounded-full bg-white/20" />
                  Non-members of the group
                </li>
                <li className="flex items-center gap-3">
                  <span className="w-1.5 h-1.5 rounded-full bg-white/20" />
                  People outside the current trip
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* 10. YOU CAN LEAVE SECTION */}
        <section className="py-24 sm:py-32 border-t border-white/10">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-4">
            MEMBERSHIP AUTONOMY
          </div>

          <h3 className="text-[30px] sm:text-5xl font-medium text-white tracking-tight leading-tight">
            YOU CAN LEAVE.
          </h3>

          <p className="mt-6 text-xs sm:text-base text-white/60 max-w-xl font-normal leading-relaxed">
            Leaving a group should never require permission from the system. Any member can leave a group at any time, and a leader can remove a member — access ends the moment membership does.
          </p>
        </section>

        {/* 11. REFINED SOS SECTION (Operational Editorial Block!) */}
        <section className="py-24 sm:py-32 border-t border-white/10">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-4">
            WHEN SOMETHING GOES WRONG
          </div>

          <div className="space-y-6 max-w-2xl">
            <h3 className="text-[28px] sm:text-4xl font-medium text-white tracking-tight">
              ONE TAP. THE GROUP KNOWS.
            </h3>

            <p className="text-xs sm:text-base text-white/70 font-normal leading-relaxed">
              When SOS is activated, standard update interval buffering is overridden to immediately broadcast high-precision coordinates to every active group member.
            </p>

            <div className="pt-2 border-t border-white/10 flex items-center justify-between font-mono text-xs">
              <div className="inline-flex items-center gap-3 py-2 text-white">
                <span className="w-2 h-2 rounded-full bg-white animate-ping" />
                <span className="font-bold">SOS ● SIGNALING GROUP</span>
              </div>
              <span className="text-white/40 text-[11px]">PRIORITY DISPATCH</span>
            </div>
          </div>
        </section>

        {/* 12. HISTORY SECTION */}
        <section className="py-24 sm:py-32 border-t border-white/10">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-4">
            DATA ARCHIVAL INTENT
          </div>

          <h3 className="text-[30px] sm:text-5xl font-medium text-white tracking-tight leading-tight">
            A TRIP CAN HAVE A HISTORY <br />
            <span className="font-serif italic font-normal text-white/85">
              WITHOUT BECOMING SURVEILLANCE.
            </span>
          </h3>

          <p className="mt-6 text-xs sm:text-base text-white/60 max-w-xl font-normal leading-relaxed">
            Trip history exists so a completed trip can be reviewed, replayed, and understood later. Live tracking closes permanently when a trip ends.
          </p>
        </section>

        {/* 13. FINAL RULES SUMMARY */}
        <section className="py-20 sm:py-28 border-t border-white/10">
          <div className="text-xs font-mono text-white/40 uppercase tracking-[0.2em] mb-8">
            THE RULES ARE SIMPLE
          </div>

          <ol className="space-y-5 text-xs sm:text-base font-sans text-white/80 max-w-2xl">
            <li className="flex items-start gap-4 border-b border-white/10 pb-4">
              <span className="font-mono text-white/40 text-xs pt-0.5">01</span>
              <span>Only the right people see location.</span>
            </li>
            <li className="flex items-start gap-4 border-b border-white/10 pb-4">
              <span className="font-mono text-white/40 text-xs pt-0.5">02</span>
              <span>Visibility follows the trip.</span>
            </li>
            <li className="flex items-start gap-4 border-b border-white/10 pb-4">
              <span className="font-mono text-white/40 text-xs pt-0.5">03</span>
              <span>Leaving is always possible.</span>
            </li>
            <li className="flex items-start gap-4 border-b border-white/10 pb-4">
              <span className="font-mono text-white/40 text-xs pt-0.5">04</span>
              <span>SOS reaches the group immediately.</span>
            </li>
            <li className="flex items-start gap-4">
              <span className="font-mono text-white/40 text-xs pt-0.5">05</span>
              <span>Trip history remains useful without becoming a live feed.</span>
            </li>
          </ol>
        </section>

      </div>

      {/* 14. FINAL CTA */}
      <section className="pb-28 px-6 max-w-3xl mx-auto text-center border-t border-white/10 pt-20">
        <h3 className="text-[24px] sm:text-4xl font-medium text-white tracking-tight">
          Know how RALLY keeps your group safe.
        </h3>

        <p className="mt-4 text-xs sm:text-base text-white/60 font-normal font-sans">
          Read the common questions or start planning your first trip.
        </p>

        <div className="mt-8 flex flex-wrap items-center justify-center gap-4 font-mono text-xs">
          <Link
            href="/faq"
            className="px-6 py-3.5 min-h-[42px] rounded-full border border-white/20 text-white hover:bg-white/10 transition-colors uppercase tracking-wider font-semibold inline-flex items-center"
          >
            FAQ →
          </Link>

          <Link
            href="/docs/getting-started"
            className="px-6 py-3.5 min-h-[42px] rounded-full bg-white text-black hover:bg-white/90 transition-colors uppercase tracking-wider font-semibold shadow-[0_0_20px_rgba(255,255,255,0.15)] inline-flex items-center"
          >
            Get Started →
          </Link>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}
