"""initial schema: postgis + profiles, groups, group_members, trips,
location_history, alerts, sos_events

Revision ID: 0001
Revises:
Create Date: 2026-08-26

Hand-written rather than autogenerated: this phase has no live Supabase
connection available to diff against. Mirrors app/models/*.py exactly —
if you change a model, update this migration (or add a new one) to match.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        # References Supabase Auth's own table. Not managed by our
        # migrations — Supabase owns the auth schema.
        sa.ForeignKeyConstraint(["id"], ["auth.users.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "groups",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("join_code", sa.String(length=20), nullable=False),
        sa.Column("leader_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("destination_name", sa.String(length=255), nullable=True),
        sa.Column("destination", Geography(geometry_type="POINT", srid=4326), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", "ARCHIVED", name="group_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["leader_id"], ["profiles.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("join_code", name="uq_groups_join_code"),
    )
    op.create_index("ix_groups_join_code", "groups", ["join_code"])

    op.create_table(
        "group_members",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.Enum("LEADER", "MEMBER", name="member_role"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "LEFT", "REMOVED", name="member_status"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_members_group_user"),
    )
    op.create_index("ix_group_members_group_id", "group_members", ["group_id"])
    op.create_index("ix_group_members_user_id", "group_members", ["user_id"])

    op.create_table(
        "trips",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        # RESTRICT: see the comment in app/models/trip.py — a group must not
        # be deletable while trip history still references it.
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("started_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CREATED", "ACTIVE", "COMPLETED", "CANCELLED", name="trip_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_location", Geography(geometry_type="POINT", srid=4326), nullable=True),
        sa.Column("destination", Geography(geometry_type="POINT", srid=4326), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("safety_score", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["started_by"], ["profiles.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_trips_group_id", "trips", ["group_id"])

    op.create_table(
        "location_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("trip_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("location", Geography(geometry_type="POINT", srid=4326), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("heading", sa.Float(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_location_history_trip_id", "location_history", ["trip_id"])
    op.create_index("ix_location_history_group_id", "location_history", ["group_id"])
    op.create_index("ix_location_history_user_id", "location_history", ["user_id"])
    op.create_index("ix_location_history_recorded_at", "location_history", ["recorded_at"])
    op.create_index(
        "ix_location_history_trip_recorded", "location_history", ["trip_id", "recorded_at"]
    )
    op.create_index(
        "ix_location_history_group_recorded", "location_history", ["group_id", "recorded_at"]
    )
    op.create_index(
        "ix_location_history_user_recorded", "location_history", ["user_id", "recorded_at"]
    )

    op.create_table(
        "alerts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("trip_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "FALLING_BEHIND",
                "GROUP_SEPARATION",
                "ROUTE_DEVIATION",
                "UNEXPECTED_STOP",
                "CONNECTIVITY_LOSS",
                "SPEED_ANOMALY",
                "SOS",
                name="alert_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("INFO", "WARNING", "HIGH", "CRITICAL", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("location", Geography(geometry_type="POINT", srid=4326), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RESOLVED", name="alert_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_alerts_group_id", "alerts", ["group_id"])
    op.create_index("ix_alerts_trip_id", "alerts", ["trip_id"])

    op.create_table(
        "sos_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("trip_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("location", Geography(geometry_type="POINT", srid=4326), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RESOLVED", "CANCELLED", name="sos_status"),
            nullable=False,
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_sos_events_group_id", "sos_events", ["group_id"])
    op.create_index("ix_sos_events_trip_id", "sos_events", ["trip_id"])


def downgrade() -> None:
    op.drop_table("sos_events")
    op.drop_table("alerts")
    op.drop_table("location_history")
    op.drop_table("trips")
    op.drop_table("group_members")
    op.drop_table("groups")
    op.drop_table("profiles")

    for enum_name in (
        "sos_status",
        "alert_status",
        "alert_severity",
        "alert_type",
        "trip_status",
        "member_status",
        "member_role",
        "group_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
